services:
    aw.settings.storage:
      alias: aw.settings.storage.doctrine

    aw.settings.storage.doctrine:
      class: Accurateweb\ApplicationSettingsAdminBundle\Model\Storage\DoctrineSettingStorage
      arguments: ['@aw.settings.repository', '@doctrine.orm.entity_manager']

    aw.settings.repository:
      class: Accurateweb\ApplicationSettingsAdminBundle\Repository\SettingRepository
      arguments: ['@doctrine', ~]

    aw.settings.configuration_pool:
      class: Accurateweb\ApplicationSettingsAdminBundle\Model\SettingConfiguration\SettingConfigurationPool

    aw.settings.manager:
      class: Accurateweb\ApplicationSettingsAdminBundle\Model\Manager\SettingManager
      factory: 'aw.settings.manager.factory:createSettingManager'
      public: true
      lazy: true

    aw.settings.manager.factory:
      class: Accurateweb\ApplicationSettingsAdminBundle\Model\Manager\SettingManagerFactory
      arguments: ['@aw.settings.configuration_pool', '@aw.settings.storage', '@event_dispatcher']
      lazy: true

    aw.twig.settings:
      class: Accurateweb\ApplicationSettingsAdminBundle\Twig\SettingsExtension
      arguments: ['@aw.settings.manager', '@aw.settings.configuration_pool']
      public: false
      autowire: false
      tags:
        - { name: twig.extension }

    aw.admin.settings:
      class: Accurateweb\ApplicationSettingsAdminBundle\Admin\SettingsAdmin
      arguments: [~, ~, ~, '@aw.settings.configuration_pool']
      calls:
        - [ setTemplate, [base_list_field, AccuratewebApplicationSettingsAdminBundle::list_field.html.twig]]
      tags:
        -  { name: sonata.admin, group: '%aw.settings.admin.group%', manager_type: orm, label: '%aw.settings.admin.label%' }

    aw.settings.persister:
      class: Accurateweb\ApplicationSettingsAdminBundle\EventListener\SettingManagerPersister
      arguments: ['@aw.settings.configuration_pool', '@aw.settings.storage', '@aw.settings.manager']
      tags:
        - { name: kernel.event_listener, event: kernel.terminate, method: onTerminate }
        - { name: kernel.event_listener, event: console.terminate, method: onConsoleTerminate }
